use_frameworks!

platform :ios, '8.0'

target 'HJQCategoryKit_Example' do
  pod 'HJQCategoryKit', :path => '../'

  target 'HJQCategoryKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
